# Generated by Django 3.0.3 on 2020-08-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dennisapp', '0002_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dennisapp.Customer'),
        ),
        migrations.AddField(
            model_name='status',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dennisapp.Product'),
        ),
    ]
