# Generated by Django 3.0.3 on 2020-08-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dennisapp', '0005_auto_20200817_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
    ]
