# Generated by Django 3.0.3 on 2020-08-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennisapp', '0003_auto_20200817_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.DateTimeField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('out for delivery', 'out for delivery')], null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='tags',
            field=models.ManyToManyField(to='dennisapp.Tag'),
        ),
    ]
