# Generated by Django 3.0.3 on 2020-08-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennisapp', '0004_auto_20200817_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='dennisapp.Tag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
