# Generated by Django 3.0.3 on 2020-09-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennisapp', '0006_auto_20200817_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('out for delivery', 'out for delivery')], max_length=200, null=True),
        ),
    ]
