# Generated by Django 3.0.3 on 2020-09-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennisapp', '0007_auto_20200906_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
